# Generated by Django 5.2 on 2025-05-07 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_bob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('bob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.bob')),
            ],
        ),
    ]
