# Generated by Django 5.2 on 2025-05-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
